(function(){
  if(window.__sxDispatchPhoneV2)return;
  window.__sxDispatchPhoneV2=true;

  const DISPATCHER='Benjamin Cole';
  const STORAGE_KEY='sx_dispatch_threads_v2';
  const META_KEY='sx_dispatch_meta_v2';
  const css=`
  #sxDispatchFab{position:fixed;right:22px;bottom:22px;z-index:2147483000;width:60px;height:60px;border-radius:19px;border:1px solid rgba(255,255,255,.18);background:linear-gradient(180deg,#1d9bf0,#0878d1);color:#fff;box-shadow:0 14px 40px rgba(0,0,0,.45);font-size:25px;cursor:pointer;display:grid;place-items:center}
  #sxDispatchFab:active{transform:scale(.96)}
  #sxDispatchBadge{position:absolute;right:-5px;top:-5px;min-width:21px;height:21px;border-radius:11px;padding:0 5px;background:#ff453a;color:#fff;font:800 11px/21px -apple-system,BlinkMacSystemFont,sans-serif;border:2px solid #0b0b0b;display:none}
  #sxDispatchPhone{position:fixed;right:22px;bottom:94px;z-index:2147482999;width:min(390px,calc(100vw - 24px));height:min(790px,calc(100vh - 118px));background:#000;border:3px solid #303035;border-radius:48px;box-shadow:0 28px 90px rgba(0,0,0,.72),inset 0 0 0 1px #0a0a0a;overflow:hidden;display:none;color:#fff;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",sans-serif}
  #sxDispatchPhone.open{display:flex;flex-direction:column}
  .sx-ios-status{height:42px;display:grid;grid-template-columns:1fr auto 1fr;align-items:center;padding:5px 18px 0;background:#090909;font-size:12px;font-weight:700;flex:0 0 auto}
  .sx-ios-time{justify-self:start}.sx-island{width:116px;height:31px;background:#000;border-radius:20px;border:1px solid #111;box-shadow:inset 0 0 0 1px #050505}.sx-ios-icons{justify-self:end;font-size:11px;letter-spacing:2px}
  .sx-d-head{padding:5px 12px 10px;border-bottom:1px solid #242424;display:grid;grid-template-columns:44px 1fr 44px;align-items:center;background:rgba(18,18,18,.96)}
  .sx-close{border:0;background:transparent;color:#0a84ff;font-size:29px;cursor:pointer;padding:3px;text-align:left;line-height:1}
  .sx-contact{text-align:center;min-width:0}.sx-avatar{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;margin:0 auto 4px;background:linear-gradient(145deg,#386080,#172a3f);font-size:13px;font-weight:800;color:#fff;border:1px solid rgba(255,255,255,.15)}
  .sx-d-name{font-size:12px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.sx-d-sub{font-size:10px;color:#8e8e93;margin-top:1px}.sx-info{color:#0a84ff;font-size:18px;text-align:right;padding-right:5px}
  .sx-tripcard{margin:9px 10px 5px;padding:10px 11px;border-radius:14px;background:#151517;border:1px solid #29292c;flex:0 0 auto}.sx-triptop{display:flex;justify-content:space-between;gap:8px;align-items:center}.sx-flight{font-size:11px;color:#0a84ff;font-weight:800;letter-spacing:.04em}.sx-state{font-size:9px;color:#30d158;font-weight:800}.sx-route{font-size:16px;font-weight:800;margin-top:3px}.sx-client{font-size:10px;color:#9a9aa0;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
  #sxDispatchMsgs{flex:1;min-height:0;overflow:auto;padding:10px 11px 16px;background:#000;scroll-behavior:smooth}.sx-day{text-align:center;color:#6e6e73;font-size:10px;margin:8px 0 14px}.sx-bubble{max-width:79%;padding:9px 12px;border-radius:19px;margin:5px 0;font-size:13px;line-height:1.34;white-space:pre-wrap;word-break:break-word}.sx-in{background:#262629;border-bottom-left-radius:6px;color:#fff}.sx-out{background:#0a84ff;color:#fff;margin-left:auto;border-bottom-right-radius:6px}.sx-time{font-size:8px;opacity:.58;margin-top:4px;text-align:right}
  #sxQuickReplies{padding:7px 9px;display:flex;gap:6px;overflow-x:auto;border-top:1px solid #202022;background:#0b0b0c;scrollbar-width:none;flex:0 0 auto}#sxQuickReplies::-webkit-scrollbar{display:none}.sx-chip{flex:0 0 auto;border:1px solid #3a3a3c;background:#171719;color:#e9e9ea;border-radius:999px;padding:7px 10px;font-size:10px;cursor:pointer}.sx-chip:active{background:#2b2b2e}
  .sx-compose{display:flex;align-items:center;gap:7px;padding:8px 10px 6px;background:#111;border-top:1px solid #242426;flex:0 0 auto}.sx-plus{width:30px;height:30px;border-radius:50%;border:0;background:#2c2c2e;color:#aaa;font-size:20px}.sx-inputwrap{flex:1;min-width:0;border:1px solid #3a3a3c;border-radius:18px;display:flex;align-items:center;background:#1c1c1e}.sx-inputwrap.disabled{opacity:.5}.sx-inputwrap input{flex:1;min-width:0;border:0;background:transparent;color:#fff;padding:8px 11px;font-size:13px;outline:none}.sx-inputwrap input::placeholder{color:#777}.sx-send{width:30px;height:30px;border-radius:50%;border:0;background:#0a84ff;color:white;font-weight:900;cursor:pointer;margin-right:3px}.sx-homebar{height:19px;background:#111;display:grid;place-items:center;flex:0 0 auto}.sx-homebar:after{content:'';width:128px;height:5px;background:#f5f5f7;border-radius:3px;display:block;opacity:.9}
  .sx-empty{padding:28px 18px;text-align:center;color:#8e8e93;font-size:12px;line-height:1.45}.sx-empty b{display:block;color:#fff;font-size:14px;margin-bottom:5px}
  @media(max-width:700px){#sxDispatchPhone{left:8px;right:8px;bottom:82px;width:auto;height:calc(100vh - 100px);max-height:none;border-radius:38px}#sxDispatchFab{right:14px;bottom:14px;width:56px;height:56px;border-radius:17px}}
  `;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);

  const fab=document.createElement('button');fab.id='sxDispatchFab';fab.innerHTML='💬<span id="sxDispatchBadge"></span>';fab.setAttribute('aria-label','Open Sierra Dispatch');
  const phone=document.createElement('div');phone.id='sxDispatchPhone';
  phone.innerHTML=`
    <div class="sx-ios-status"><div class="sx-ios-time" id="sxPhoneClock">9:41</div><div class="sx-island"></div><div class="sx-ios-icons">▮▮▮ ᯤ ▰</div></div>
    <div class="sx-d-head"><button class="sx-close" aria-label="Close">‹</button><div class="sx-contact"><div class="sx-avatar">BC</div><div class="sx-d-name">${DISPATCHER}</div><div class="sx-d-sub">Sierra Dispatch</div></div><div class="sx-info">ⓘ</div></div>
    <div class="sx-tripcard"><div class="sx-triptop"><div class="sx-flight" id="sxTripFlight">NO ACTIVE FLIGHT</div><div class="sx-state" id="sxTripState">STANDBY</div></div><div class="sx-route" id="sxTripRoute">Sierra Executive</div><div class="sx-client" id="sxTripClient">Accept a charter to start a dispatch thread.</div></div>
    <div id="sxDispatchMsgs"></div><div id="sxQuickReplies"></div>
    <div class="sx-compose"><button class="sx-plus" aria-label="More">+</button><div class="sx-inputwrap" id="sxInputWrap"><input id="sxDispatchInput" placeholder="iMessage" autocomplete="off"><button class="sx-send" id="sxDispatchSend">↑</button></div></div><div class="sx-homebar"></div>`;
  document.body.appendChild(phone);document.body.appendChild(fab);

  const q=s=>document.querySelector(s),msgs=q('#sxDispatchMsgs'),badge=q('#sxDispatchBadge'),input=q('#sxDispatchInput');
  let isOpen=false,unread=0,opsTimer=null,lastTripKey='';

  function appState(){try{return (typeof state!=='undefined'&&state)?state:JSON.parse(localStorage.getItem('sierra_phenom300_state')||'{}')}catch(e){return {}}}
  function activeTrip(){const s=appState();let a=s.activeAssignment||s.activeFlight||s.currentFlight||null;if(!a&&Array.isArray(s.marketBoard))a=s.marketBoard.find(x=>x&&String(x.status).toLowerCase()==='accepted')||null;return a||null}
  function tripKey(a){return String((a&& (a.flight||a.id||a.callsign))||'general').toUpperCase()}
  function allThreads(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')||{}}catch(e){return {}}}
  function thread(a){const all=allThreads();return all[tripKey(a)]||[]}
  function saveThread(a,t){const all=allThreads();all[tripKey(a)]=t.slice(-120);localStorage.setItem(STORAGE_KEY,JSON.stringify(all))}
  function meta(){try{return JSON.parse(localStorage.getItem(META_KEY)||'{}')||{}}catch(e){return {}}}
  function saveMeta(x){localStorage.setItem(META_KEY,JSON.stringify(x||{}))}
  function now(){return new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}
  function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function route(a){return a?[a.origin,a.dest||a.destination].filter(Boolean).join(' → '):''}
  function classify(a){const text=[a&&a.category,a&&a.charterType,a&&a.client,a&&a.event].join(' ').toLowerCase();if(/athlete|sports|team|player|arena|golf/.test(text))return'sports';if(/celebrity|artist|talent|music|record|production|media|entertain/.test(text))return'talent';if(/vip|family office|principal|security|private office/.test(text))return'vip';return'exec'}
  function add(a,who,text,quiet){if(!a)return;const t=thread(a);t.push({who,text:String(text),time:now(),ts:Date.now()});saveThread(a,t);if(who==='dispatch'&&!isOpen&&!quiet){unread++;updateBadge()}if(isOpen)renderMessages()}
  function updateBadge(){badge.textContent=unread>9?'9+':String(unread);badge.style.display=unread?'block':'none'}
  function seed(a){if(!a||thread(a).length)return;const c=classify(a),client=a.client||'the client',rt=route(a)||'your trip';const intro=`I have ${rt}${a.flight?' as '+a.flight:''} on my board. I’ll track passengers, FBO handling, ground transportation and schedule changes.`;add(a,'dispatch',intro,true);if(c==='sports')add(a,'dispatch',`Sports movement noted. I’m tracking passenger timing and baggage/equipment for ${client}.`,true);else if(c==='talent')add(a,'dispatch',`Talent movement noted. I’m tracking discreet boarding, passenger ETA and handling for ${client}.`,true);else if(c==='vip')add(a,'dispatch',`VIP movement noted. I’m tracking privacy, vehicle timing and handling for ${client}.`,true);else add(a,'dispatch',`Executive charter noted. I’m tracking passenger ETA, car service and FBO handling for ${client}.`,true)}
  function renderHeader(){const a=activeTrip();const s=appState();q('#sxTripFlight').textContent=a?(a.flight||'ACTIVE FLIGHT'):'NO ACTIVE FLIGHT';q('#sxTripState').textContent=a?String(s.workflow||a.status||'ACTIVE').toUpperCase():'STANDBY';q('#sxTripRoute').textContent=a?(route(a)||'Active charter'):'Sierra Executive';q('#sxTripClient').textContent=a?(a.client||a.charterType||'Private charter'):'Accept a charter to start a dispatch thread.';const disabled=!a;input.disabled=disabled;q('#sxInputWrap').classList.toggle('disabled',disabled);input.placeholder=disabled?'No active charter':'iMessage'}
  function renderMessages(){const a=activeTrip();renderHeader();if(!a){msgs.innerHTML='<div class="sx-empty"><b>Dispatch is standing by</b>Accept a charter and the active flight will automatically appear here.</div>';q('#sxQuickReplies').innerHTML='';return}seed(a);const t=thread(a);msgs.innerHTML='<div class="sx-day">SIERRA EXECUTIVE • DISPATCH</div>'+t.map(m=>`<div class="sx-bubble ${m.who==='me'?'sx-out':'sx-in'}">${esc(m.text)}<div class="sx-time">${esc(m.time)}</div></div>`).join('');msgs.scrollTop=msgs.scrollHeight;renderQuick(a)}
  function renderQuick(a){const c=classify(a);let items=['Passenger status','FBO status','Fuel status','Ground transport','Ready to push'];if(c==='talent')items=['Passenger ETA','Discreet boarding','Catering status','Ground transport','Ready to push'];if(c==='sports')items=['Player ETA','Bags/equipment','SUV status','FBO status','Ready to push'];if(c==='vip')items=['Principal ETA','Security status','SUV status','FBO status','Ready to push'];q('#sxQuickReplies').innerHTML=items.map(x=>`<button class="sx-chip" data-msg="${esc(x)}">${esc(x)}</button>`).join('');q('#sxQuickReplies').querySelectorAll('.sx-chip').forEach(b=>b.onclick=()=>send(b.dataset.msg))}
  function response(a,text){const c=classify(a),l=text.toLowerCase(),dest=a.dest||a.destination||'destination';if(/ready|push/.test(l))return'Copy. I have you marked ready. I’ll flag anything that changes before push.';if(/weather/.test(l))return`I’m checking the weather package for ${dest}. I’ll flag anything that affects timing, runway planning or the release.`;if(/fuel/.test(l))return'Fuel is on the ops list. I’ll track the requested uplift and FBO confirmation before departure.';if(/fbo|handling/.test(l))return'FBO handling is being tracked. I’ll keep passenger arrival, baggage, fuel and ground services tied to this trip.';if(/cater/.test(l))return c==='talent'?'Catering is tied to the client profile. I’ll flag any rider or last-minute change.':'Catering is being tracked with the FBO. I’ll confirm when it is marked delivered.';if(/suv|transport|car/.test(l))return'Ground transportation is being tracked. I’ll send the vehicle status and pickup point when confirmed.';if(/passenger|player|principal|eta/.test(l))return c==='sports'?'I’m tracking the player/passenger movement. I’ll message when the vehicle is actually inbound.':c==='talent'?'Management timing is being tracked. I’ll send the actual curb/ramp ETA when it firms up.':c==='vip'?'Security timing is being tracked. I’ll send the principal vehicle window when it checks in.':'Passenger timing is being tracked. I’ll send the actual arrival estimate when dispatch gets it.';if(/bag|equipment/.test(l))return'I have the baggage/equipment note on the trip. I’ll flag anything that affects loading or cabin planning.';if(/security|discreet|privacy/.test(l))return'Understood. Privacy handling is noted and I’ll keep the boarding/FBO coordination discreet.';if(/delay|late/.test(l))return'Copy. I’m marking the delay and protecting downstream services. Send me the revised estimate when you have it.';return'Copy. I’ve got it on the active trip and I’ll flag anything operationally important.'}
  function send(text){const a=activeTrip();text=String(text||input.value||'').trim();if(!a||!text)return;add(a,'me',text,true);input.value='';const sentKey=tripKey(a);setTimeout(()=>{const current=activeTrip();if(current&&tripKey(current)===sentKey)add(current,'dispatch',response(current,text))},500+Math.random()*650)}
  function scheduleOps(){clearTimeout(opsTimer);const a=activeTrip();if(!a)return;const key=tripKey(a),c=classify(a),bank={sports:['Passenger timing is still holding. I’ll message when the vehicle checks in.','Ground team has the baggage/equipment note. No schedule change right now.'],talent:['Client still wants discreet boarding. The handling note is on the trip.','Passenger window is still holding. I’ll send the vehicle ETA when confirmed.'],vip:['Security/privacy handling is on the trip. I’ll message when the principal vehicle is inbound.','SUV coordination is still on schedule. No change to wheels-up right now.'],exec:['Passenger timing is holding. Car service and FBO handling are still tracking.','No schedule change right now. I’ll flag any client movement on wheels-up.']};opsTimer=setTimeout(()=>{const current=activeTrip();if(!current||tripKey(current)!==key)return scheduleOps();const arr=bank[c]||bank.exec;add(current,'dispatch',arr[Math.floor(Math.random()*arr.length)]);scheduleOps()},150000+Math.random()*120000)}
  function refresh(){q('#sxPhoneClock').textContent=now();const a=activeTrip(),k=tripKey(a);renderHeader();if(k!==lastTripKey){lastTripKey=k;if(a)seed(a);renderMessages();scheduleOps();const m=meta();m.lastTrip=k;saveMeta(m)}else if(isOpen){renderMessages()}}
  function openPhone(){isOpen=true;phone.classList.add('open');unread=0;updateBadge();renderMessages();setTimeout(()=>{if(!input.disabled)input.focus()},120)}
  function closePhone(){isOpen=false;phone.classList.remove('open')}

  fab.onclick=()=>isOpen?closePhone():openPhone();q('.sx-close').onclick=closePhone;q('#sxDispatchSend').onclick=()=>send();input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();send()}});
  window.sxDispatchPhone={open:openPhone,close:closePhone,refresh:refresh};
  refresh();scheduleOps();setInterval(refresh,2500);
})();